### ISSUE TITLE
Specs failing due to different locale

### ISSUE THREAD

**Issue by 0mega** [thibaudgg/video_info#105] opened 2015-09-04 22:14 UTC
```
Failures:

  1) VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #title should eq "YouTube Policy and Copyright"
     Failure/Error: it { is_expected.to eq 'YouTube Policy and Copyright' }
       
       expected: "YouTube Policy and Copyright"
            got: "Política do YouTube e direitos de autor"
       
       (compared using ==)
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:87:in `block (4 levels) in <top (required)>'

  2) VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #description should eq "Learn more about copyright basics, flagging, and the YouTube community."
     Failure/Error: it { is_expected.to eq 'Learn more about copyright basics, flagging, and the YouTube community.' }
       
       expected: "Learn more about copyright basics, flagging, and the YouTube community."
            got: "Saiba mais acerca das noções básicas de direitos de autor, das denúncias e da comunidade YouTube."
       
       (compared using ==)
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:92:in `block (4 levels) in <top (required)>'

  3) VideoInfo::Providers::Youtube with video mZqGqE0D0n4 #view_count should be > 4000
     Failure/Error: it { is_expected.to be > 4000 }
       expected: > 4000
            got:   6
     # ./spec/lib/video_info/providers/youtube_spec.rb:207:in `block (4 levels) in <top (required)>'

  4) VideoInfo::Providers::Youtube with full screen video URLs #view_count should be > 4000
     Failure/Error: it { is_expected.to be > 4000 }
       expected: > 4000
            got:   6
     # ./spec/lib/video_info/providers/youtube_spec.rb:477:in `block (4 levels) in <top (required)>'

Finished in 6.95 seconds (files took 0.58402 seconds to load)
399 examples, 4 failures, 1 pending
```

I tried sufixing the URLs with hl=en [based on this doc](https://developers.google.com/youtube/player_parameters?hl=en#hl) but nothing changed.

**Comment by vheuken** [comment] 2015-09-04 22:34
Looks like with `hl=` you end up getting this:

![ ] (http://i.imgur.com/0Gdj6v2.png)

Which you need to click before it works.

I wouldn't spend too much time on this. Might be best to just have the specs to use non-localized videos/playlists.

**Comment by vheuken** [comment] 2016-03-02 03:36
Closing because this is not a bug with the library. If this affects anyone, they can manually look at the output or just use Travis-CI.

**Closed by vheuken** 2016-03-02 03:36 UTC
