### ISSUE TITLE
The youtube video duration is wrong

### ISSUE THREAD

**Issue by mwanas** [thibaudgg/video_info#70] opened 2015-05-11 10:41 UTC
Trying any video duration is always giving 236 sec

**Comment by thibaudgg** [comment] 2015-05-11 11:39
Hey thanks for opening this issue, it could be related to https://github.com/thibaudgg/video_info/pull/68

**Comment by mwanas** [comment] 2015-05-11 11:47
what should I do to fix the issue ?

**Comment by thibaudgg** [comment] 2015-05-11 12:14
I would wait that #68 has been merged, maybe you can try the branch in the meantime.

**Comment by vheuken** [comment] 2015-05-11 22:06
@mwanas The issue is fixed on my branch so you can grab that code if you want.  You'll need to grab a youtube API key, though. There is documentation in the README in my branch on how to do this.

**Comment by thibaudgg** [comment] 2015-05-12 06:50
@vheuken :+1:, thanks!

**Comment by thibaudgg** [comment] 2015-05-14 20:05
@mwanas could you try the master branch and confirm that it works for you now? Thanks!

**Closed** 2015-06-02 06:42 UTC
