### ISSUE TITLE
Unable to pull YouTube Title, Description, Duration, and Date

### ISSUE THREAD

**Issue by gbean467** [thibaudgg/video_info#98] opened 2015-08-19 02:04 UTC
Ever since the API change by YouTube I haven't been able to get the title, description, or date of any videos. The duration is also not working as it always returns a value of 0. The available also appears broken as it always returns false (as noted in other issues). The video_id, provider, thumbnails, etc. have all been working just fine. I was excited for the latest release (2.5.0), but it didn't seem to fix the issue.

**Comment by vheuken** [comment] 2015-08-19 02:08
That's odd. Are you using the scraper or the API?

Are you sure you're using 2.5.0? Try this and see if it helps:

```
gem uninstall video_info
bundle clean
bundle install
```

**Comment by gbean467** [comment] 2015-08-19 02:22
I uninstalled all version of video_info, cleaned, and reinstalled. It doesn't seem to have changed anything. I am pretty sure I am using the API. My code is as follows:

    VideoInfo.provider_api_keys = { youtube: '<MYKEY>' }
    begin
      video = VideoInfo.new(url)
    rescue
      errors.add(:url, "URL link is not valid")
      return
    end
    puts(video.available?)
    if !video.available?
      begin
        self.title = video.title.to_s

        puts("Video ID: " + video.video_id.to_s)
        puts("Provider: " + video.provider.to_s)
        puts("Title: " + video.title.to_s) # Not working
        puts("Description: " + video.description.to_s) # Not working
        puts("Duration: " + video.duration.to_s) # Not working
        puts("Date: " + video.date.to_s) # Not working
        puts("Small thumbnail: " + video.thumbnail_small.to_s)
        puts("Medium thumbnail: " + video.thumbnail_medium.to_s)
        puts("Large thumbnail: " + video.thumbnail_large.to_s)
        puts(video.embed_url)
        puts(video.embed_code)
        puts(video.embed_url)

        self.image_url = video.thumbnail_small
      rescue
        errors.add(:url, "Error loading URL data")
        return
      end
    else
        errors.add(:url, "Video link is not valid")
    end

**Comment by vheuken** [comment] 2015-08-19 02:27
Can you try it with the scraper? To use the scraper, just delete the first line `VideoInfo.provider_api_keys = { youtube: '<MYKEY>' }`

I just tried it with the scraper and it worked fine:
```ruby
2.2.2 :003 > a = VideoInfo.new('https://www.youtube.com/watch?v=BwSoPjRhJpc')
 => #<VideoInfo:0x00000001a67308 @provider=#<VideoInfo::Providers::Youtube:0x00000001a66a70 @options={"User-Agent"=>"VideoInfo/2.5.0"}, @url="https://www.youtube.com/watch?v=BwSoPjRhJpc", @video_id="BwSoPjRhJpc">> 
2.2.2 :004 > a.duration
 => 1835 
2.2.2 :005 > a = VideoInfo.new('https://www.youtube.com/watch?v=cxk-cs6n_K0')
 => #<VideoInfo:0x000000008d37e0 @provider=#<VideoInfo::Providers::Youtube:0x000000008d1850 @options={"User-Agent"=>"VideoInfo/2.5.0"}, @url="https://www.youtube.com/watch?v=cxk-cs6n_K0", @video_id="cxk-cs6n_K0">> 
2.2.2 :006 > a.duration
 => 11 
2.2.2 :007 > a.date
 => 2013-11-30 00:00:00 -0800 
2.2.2 :008 > a.title
 => "shoegaze.mov" 
2.2.2 :009 > a.description
 => "[vacuuming intensifies]" 
```

**Comment by gbean467** [comment] 2015-08-19 02:38
Deleting the first line gives me the following error:
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Is this related?

**Comment by gbean467** [comment] 2015-08-19 03:16
The SSL error only happens when I try to pull available, date, duration, title, and description (same as API).

**Comment by vheuken** [comment] 2015-08-19 03:22
Huh, this is very odd. 

Could you try cloning this repository, running rspec, and seeing if the tests pass?

**Comment by gbean467** [comment] 2015-08-19 03:50
Assuming I did this right I 366 examples, 96 failures, 1 pending. What information would be beneficial?

**Comment by gbean467** [comment] 2015-08-19 03:52
It looks like this error is consistent:
    OpenSSL::SSL::SSLError:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

**Comment by vheuken** [comment] 2015-08-19 04:44
>Assuming I did this right I got 366 examples, 96 failures, 1 pending. What information would be beneficial?

The tests all pass on my machine, Travis-CI, and other people's machines, so the issue seems to be unique to your PC. So I don't think I'll be able to reproduce it.

It looks like your issue has been discussed here: http://stackoverflow.com/questions/4528101/ssl-connect-returned-1-errno-0-state-sslv3-read-server-certificate-b-certificat

Have you looked into any of the solutions posted there?

**Comment by gbean467** [comment] 2015-08-19 14:52
I tried a few simple solutions. I'll give it some more solid effort later today.

**Comment by gbean467** [comment] 2015-08-21 00:47
I've tried updating openssl on my computer, adding certs, removing and reinstalling gems, and so on, but nothing seems to work. In the end I think it could likely be because I am coding on a Windows machine.
 
http://stackoverflow.com/questions/8567973/why-does-accessing-a-ssl-site-with-mechanize-on-windows-fail-but-on-mac-work

But after making all these changes on my local machine I re-deployed and looks the like gem is working exactly as expected on my live site!

**Comment by vheuken** [comment] 2015-08-21 04:15
Cool. Sorry it won't work on your Windows machine. Since the issue appears to be outside the scope of video_info, I'm closing this issue.

**Closed by vheuken** 2015-08-21 04:15 UTC

**Comment by YXsagittarius** [comment] 2015-08-22 18:17
With the same problem, and I'm using mac, could you help me?

**Comment by vheuken** [comment] 2015-08-23 01:03
@YXsagittarius StackOverflow would probably be a better place to ask.
